# ============================================
# VIRTUALHOST HTTP - TECHSOLUTIONS S.L.
# Redirige todo el tráfico HTTP a HTTPS
# ============================================
<VirtualHost *:80>
    ServerName techsolutions.local
    DocumentRoot /var/www/techsolutions

    # Redirigir todo el tráfico HTTP a HTTPS
    # Nadie debe usar la web sin cifrar
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]

    ErrorLog  ${APACHE_LOG_DIR}/techsolutions_error.log
    CustomLog ${APACHE_LOG_DIR}/techsolutions_access.log combined
</VirtualHost>